{"uid":"5e03db5c841576d4","name":"An uncaught error was detected outside of a test","fullName":"cypress/e2e/2-advanced-examples/navigation.cy.js#An uncaught error was detected outside of a test","historyId":"3dfff3cfae7fb46224c81ea7026bb8b7:d41d8cd98f00b204e9800998ecf8427e","time":{"start":1711463370856,"stop":1711463370936,"duration":80},"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.Allure is undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Cypress.Allure is undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\nat <unknown> (webpack://cypress_learn_project/./cypress/support/e2e.js:24:0)\nat <unknown> (https://example.cypress.io/__cypress/tests?p=cypress/support/e2e.js:234:3)\nat <unknown> (https://example.cypress.io/__cypress/tests?p=cypress/support/e2e.js:236:12)\nat __webpack_modules__</evalScripts (https://example.cypress.io/__cypress/runner/cypress_runner.js:110838:23)\nat tryCatcher (https://example.cypress.io/__cypress/runner/cypress_runner.js:1807:23)\nat gotValue (https://example.cypress.io/__cypress/runner/cypress_runner.js:6476:18)\nat gotAccum (https://example.cypress.io/__cypress/runner/cypress_runner.js:6465:25)\nat tryCatcher (https://example.cypress.io/__cypress/runner/cypress_runner.js:1807:23)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (https://example.cypress.io/__cypress/runner/cypress_runner.js:1519:31)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromise (https://example.cypress.io/__cypress/runner/cypress_runner.js:1576:18)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromiseCtx (https://example.cypress.io/__cypress/runner/cypress_runner.js:1613:10)\nat _drainQueueStep (https://example.cypress.io/__cypress/runner/cypress_runner.js:2411:12)\nat _drainQueue (https://example.cypress.io/__cypress/runner/cypress_runner.js:2400:24)\nat __webpack_modules__</Async.prototype._drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:2416:16)\nat __webpack_modules__</Async/this.drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:2286:14)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Cypress.Allure is undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Cypress.Allure is undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\nat <unknown> (webpack://cypress_learn_project/./cypress/support/e2e.js:24:0)\nat <unknown> (https://example.cypress.io/__cypress/tests?p=cypress/support/e2e.js:234:3)\nat <unknown> (https://example.cypress.io/__cypress/tests?p=cypress/support/e2e.js:236:12)\nat __webpack_modules__</evalScripts (https://example.cypress.io/__cypress/runner/cypress_runner.js:110838:23)\nat tryCatcher (https://example.cypress.io/__cypress/runner/cypress_runner.js:1807:23)\nat gotValue (https://example.cypress.io/__cypress/runner/cypress_runner.js:6476:18)\nat gotAccum (https://example.cypress.io/__cypress/runner/cypress_runner.js:6465:25)\nat tryCatcher (https://example.cypress.io/__cypress/runner/cypress_runner.js:1807:23)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (https://example.cypress.io/__cypress/runner/cypress_runner.js:1519:31)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromise (https://example.cypress.io/__cypress/runner/cypress_runner.js:1576:18)\nat __webpack_modules__</module.exports/Promise.prototype._settlePromiseCtx (https://example.cypress.io/__cypress/runner/cypress_runner.js:1613:10)\nat _drainQueueStep (https://example.cypress.io/__cypress/runner/cypress_runner.js:2411:12)\nat _drainQueue (https://example.cypress.io/__cypress/runner/cypress_runner.js:2400:24)\nat __webpack_modules__</Async.prototype._drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:2416:16)\nat __webpack_modules__</Async/this.drainQueues (https://example.cypress.io/__cypress/runner/cypress_runner.js:2286:14)","steps":[],"attachments":[{"uid":"40f8c70734c0a23a","name":"Screenshot","source":"40f8c70734c0a23a.png","type":"image/png","size":43480}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"d03451a31499d9a7","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot read properties of undefined (reading 'reporter')\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1711463354926,"stop":1711463355103,"duration":177}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5e03db5c841576d4.json","parameterValues":[]}